import { test, expect } from "@playwright/test";

// Milestone 3 acceptance criteria (design doc Section 14):
//   - Domain filter narrows list correctly
//   - Critical findings visually highlighted
//   - Detail view shows correct certificate fields
// Runs against the real backend + the fixture set generated by
// backend/fixtures/generate_fixtures.py -- domain names below match those
// fixtures exactly.

test.describe("watchlist", () => {
  test("loads the domain list from the API", async ({ page }) => {
    await page.goto("/");
    const rows = page.getByTestId("domain-row");
    await expect(rows).toHaveCount(await rows.count());
    await expect(rows.first()).toBeVisible();
    await expect(page.getByText("valid.example.com")).toBeVisible();
  });

  test("critical findings banner highlights critical issues", async ({ page }) => {
    await page.goto("/");
    const banner = page.getByTestId("findings-banner");
    await expect(banner).toBeVisible();
    await expect(banner).toContainText(/critical finding/i);

    // The expired leaf certificate is a known critical fixture case.
    await expect(page.getByTestId("critical-finding").filter({ hasText: "expired-leaf" })).toBeVisible();
  });

  test("search box narrows the domain list", async ({ page }) => {
    await page.goto("/");
    const rows = page.getByTestId("domain-row");
    const initialCount = await rows.count();
    expect(initialCount).toBeGreaterThan(1);

    await page.getByTestId("domain-search").fill("expired");

    await expect(rows).toHaveCount(1);
    await expect(rows.first()).toContainText("expired.example.com");
  });

  test("severity filter narrows the domain list to criticals only", async ({ page }) => {
    await page.goto("/");
    await page.getByTestId("severity-filter").selectOption("critical");

    const rows = page.getByTestId("domain-row");
    const count = await rows.count();
    expect(count).toBeGreaterThan(0);

    for (let i = 0; i < count; i++) {
      await expect(rows.nth(i).locator(".severity-pill")).toHaveText("critical");
    }
  });

  test("selecting a domain shows correct certificate detail fields", async ({ page }) => {
    await page.goto("/");
    await page.getByTestId("domain-search").fill("expired.example.com");
    await page.getByTestId("domain-row").first().click();

    const detail = page.getByTestId("certificate-detail");
    await expect(detail).toBeVisible();
    await expect(detail).toContainText("expired.example.com");
    await expect(detail).toContainText("expired"); // expiry_status
    await expect(detail).toContainText("Chain valid");
  });

  test("switching between certificates in a multi-cert domain updates the detail view", async ({
    page,
  }) => {
    await page.goto("/");
    await page.getByTestId("domain-search").fill("valid.example.com");
    await page.getByTestId("domain-row").first().click();

    const detail = page.getByTestId("certificate-detail");
    await expect(detail).toBeVisible();

    const pickerButtons = page.getByTestId("cert-picker-button");
    await expect(pickerButtons).toHaveCount(3); // leaf + intermediate + root

    await pickerButtons.filter({ hasText: "valid-root" }).click();
    await expect(detail).toContainText("Root CA 1");
  });
});
